### ISSUE TITLE
Model Parameters in output config not reloading between analyses

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisUI#299]
**IMPORTANT: Please apply the relevant labels, for example if this issue is needed as a backported fix add the label `LTS fix` (Long term support fix)

## Issue Description
when creating a new analysis and navigating to the output screen, the details from the previous analysis are cached

## Steps to Reproduce (Bugs only)

1. create an analysis
2. run it
3. create a new analysis on a different model
4. inspect the output settings
![image](https://user-images.githubusercontent.com/11682391/199465833-4de65cc0-0709-4de5-a741-d6a0dd6ae424.png)

## Version / Environment information
1.11.5rc1

**Comment by RolandASc** [comment]
If the model doesn't have any specific params, i.e. no **event set**, **event occurrence** and no other custom additional params, we currently skip the reloading here. This can be fixed easily.

A separate issue is that we do not clear / update the entries for the generic params `loss threshold` and the 3 new list config elements. Shall we do this in any case (re-run, template, new), or is there a purpose of keeping them when switching to a new analysis that doesn't have any previous configuration yet? Because maybe someone would like to keep running with the same set of values for the 3 new list configs?

Either way is fine from an implementation perspective, just let me know @benhayes21

**Comment by benhayes21** [comment]
i think clear it
