### ISSUE TITLE
Flamingo incremental panel, plus button 

### ISSUE THREAD

**Issue by fvitalini** [OasisLMF/OasisUI#34]
In the Flamingo incremental panel, clicking on the plus button in the header should not remove the plot in the panel.
Moreover decide whether the plus button should or should not be visible once the panel has been added. In case of not visible, the plus button will still be available on the New plot panel at the bottom.

**Comment by riccardoporreca** [comment]
Existing plots disappear upon addition or removal of incremental panels due to the reactivity of the `active` input to module `panelOutputModule()` via `inputplottype`. This is due to the fact that `active`  is invalidated by any change to the `panels_state` reactive vector.
This can be fixed by storing the state of individual panels as elements of a `reactiveValues` `panels_state` instead of a single `reactiveVal` vector.

**Comment by riccardoporreca** [comment]
@nfarabullini, @fvitalini, I have done the changes in my own fork, ready to be merged back to this repo's branch via #43. You can then assess it there and merge it to develop.
